name: Platform UI pre merge hooks
on:
  # Triggers the workflow on pull request events is opened, synchronize, or reopened to Platform UI component folder
  pull_request:

env:
  ROOT_DIRECTORY: design-system

defaults:
  run:
    # env variables not working in working-directory
    working-directory: design-system

jobs:
  check-changelog:
    name: Check for changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if changelog is required
        # Get the list of workspaces defined in package.json, and strip away the characters: [ ] ' ,
        # Check if there are any code changes in the defined workspaces.
        run: |
          workspaces=$(node -pe "require('./package.json').workspaces" | sed -e 's/[]\[\,'\'']/''/g')
          if git diff --name-only --exit-code origin/main -- ${workspaces}; then
            echo "requires_changelog=false" >> $GITHUB_ENV
            echo "Changelog not required!"
          else
            echo "requires_changelog=true" >> $GITHUB_ENV
            echo "Changelog is required. Proceed to check for changelog..."
          fi

      - name: Check for newly added changelog if required
        if: ${{ env.requires_changelog == 'true' }}
        run: |
          if git diff --name-only --diff-filter=A --exit-code origin/main -- '.changeset/*.md'; then
            echo "Error: No changelog found in .changeset folder. Please add a changelog."
            exit 1
          else
            echo "Changelog found! Proceeding..."
          fi
