name: Platform UI pre merge hooks
on:
  # Triggers the workflow on pull request events is opened, synchronize, or reopened to Platform UI component folder
  pull_request:

env:
  ROOT_DIRECTORY: design-system

defaults:
  run:
    # env variables not working in working-directory
    working-directory: design-system

jobs:
  check-changelog:
    name: Check for changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: do nothing
        run: echo 'do nothing'
